import comm from "../../../utils/comm";

const actions = {
    sendNum:({commit,state},num)=>{
        commit('sendNum',num);
    },
    getBaseCaseInfo:({commit,state},type)=>{
       commit("getBaseCaseInfo");
    },
    setTopNavTitle:({commit,state},titleName)=>{
        commit("setTopNavTitle",titleName);
    },
    saveEditType:({commit,state},type)=>{
        commit('saveEditType',type);
    },
    saveNavTopHeight:({commit,state},num)=>{
        commit('saveNavTopHeight',num);
    },
    saveCaseId:({commit,state},num)=>{
        commit('saveCaseId',num);
    },
    addSubPage:({commit,state})=>{
      commit("addSubPage");
    },
    getTeamList:({commit,state},callBack)=>{
        commit('getTeamList',callBack);
    },
    changeComponentTestResult:({commit,state},option)=>{
        commit("changeComponentTestResult",option);
    },
    changeTemplateId:({commit,state},status)=>{
      commit('changeTemplateId',status);
    },
    changeBaseHandleType:({commit,state},status)=>{
        commit('changeBaseHandleType',status);
    },
    clickChangeBtn:({commit,state})=>{
        commit("clickChangeBtn");
    },
    initUploadState:({commit,state})=>{
      commit('initUploadState');
    },
    changeUploadError:({commit,state},opt)=>{
      commit('changeUploadError',opt);
    },
    saveTemplateId:({commit,state},id)=>{
      commit('saveTemplateId',id);
    },
    getTabList:({commit,state})=>{
        commit('getTabList');
    },
    changeHandleType:({commit,state},option)=>{
      commit("changeHandleType",option);
    },
    changeIndex:({commit,state},options)=>{
        commit('changeIndex',options);
    },
    saveBasePageInfo:({commit,state},data)=>{
        commit('saveBasePageInfo',data);
    },
    savePageData:({commit,state},data)=>{
        commit('savePageData',data);
    },
    saveSubPageData:({commit,state},data)=>{
        commit('saveSubPageData',data);
    },
    saveIndexSubPageData:({commit,state})=>{
      commit('saveIndexSubPageData');
    },
    saveCopyModelData:({commit,state},data)=>{
        commit('saveCopyModelData',data);
    },
    addSubPageData:({commit,state},data)=>{
      commit('addSubPageData',data);
    },
    changeSubIndex:({commit,state},index)=>{
        commit("changeSubIndex",index);
    },
    showLayer:({commit,state},index)=>{
      commit('showLayer',index);
    },
    hideLayer:({commit,state})=>{
        commit('hideLayer');
    },
    changeNumberModuleCount:({commit,state})=>{
        commit('changeNumberModuleCount');
    },
    setNumberModuleCount:({commit,state},num)=>{
      commit('setNumberModuleCount',num);
    },
    changeNumberList:({commit,state},option)=>{
        commit('changeNumberList',option);
    },
    changeComponentData:({commit,state},options)=>{
        commit("changeComponentData",options);
    },
    changeNumberTrigger:({commit,state})=>{
        commit("changeNumberTrigger");
    },
    emptyNumberList:({commit,state})=>{
        commit("emptyNumberList");
    },
    changeSelectIndexJson:({commit,state},data)=>{
      commit("changeSelectIndexJson",data);
    },
    saveTagId:({commit,state},id)=>{
        commit('saveTagId',id);
    },
    updateTagId:({commit,state},id)=>{
      commit('updateTagId',id);
    },
    wantChangePageIndex:({commit,state},index)=>{
      commit('wantChangePageIndex',index);
    },
    saveCaseDataId:({commit,state},id)=>{
        commit('saveCaseDataId',id);
    },
    examineBasePageData:({commit,state})=>{
        commit('examineBasePageData');
    },
    checkRelationship:({commit,state},data)=>{
        commit('checkRelationship',data);
    },
    filtrateBaseData:({commit,state},data)=>{
        commit('filtrateBaseData');//过滤出新建病历首页保存的基本数据格式
    },
    showLoading:({commit,state})=>{
        commit('showLoading');
    },
    hideLoading:({commit,state})=>{
        commit('hideLoading');
    },
    examinePageData:({commit,state})=>{
        commit('examinePageData');
    },
    saveDoctorId:({commit,state},doctorId)=>{
        commit('saveDoctorId',doctorId);
    },
    operationLog:({commit,state},type)=>{
        commit('operationLog',type);
    },
    globalEventActions:({commit,state})=>{
        commit('globalEventActions');
    },
    changeSaveStatus:({commit,state},status)=>{
        commit('changeSaveStatus',status);
    },
    checkChangeState:({commit,state},type)=>{
        commit('checkChangeState',type);
    },
    changeTemTeam:({commit,state},data)=>{
        commit('changeTemTeam',data);
    },
    changeUploadState:({commit,state},opt)=>{
        commit('changeUploadState',opt);
    },
    changeAssemblePage:({commit,state},status)=>{
        commit('changeAssemblePage',status);
    },
    toast:({commit,state},text)=>{
        commit('toast',text);
    },
    templateIdType:({commit,state},type)=>{
        commit('templateIdType',type);
    },
    changeCaseBelong:({commit,state},type)=>{
        commit('changeCaseBelong',type);
    },
    changeCaseBelongCid:({commit,state},cid)=>{
        commit('changeCaseBelongCid',cid);
    },
    saveTagIdSelectList:({commit,state},opt)=>{
        commit('saveTagIdSelectList',opt);
    },
    saveBaseInfoTagIdSelectList:({commit,state},opt)=>{
        commit('saveBaseInfoTagIdSelectList',opt);
    },
    timingLog:({commit,state})=>{
        commit('timingLog');
    }

}
export default actions;
