const  actions = {
  titleNameChange:({commit,state},str)=>{
    commit("titleNameChange",str);
  },
  getReportDetail:({commit,state},opt)=>{
    commit("getReportDetail",opt);
  },
  changeVerifyPhoneNumber:({commit,state},status)=>{
    commit('changeVerifyPhoneNumber',status);
  },
  changeHasReport:({commit,state},status)=>{
    commit('changeHasReport',status);
  },
  changeClickAble:({commit,state},status)=>{
    commit('changeClickAble',status);
  },
  changeName:({commit,state},name)=>{
    commit('changeName',name);
  },
  changeIdentityCardNum:({commit,state},num)=>{
    commit('changeIdentityCardNum',num);
  },
  changePhoneNum:({commit,state},num)=>{
    commit('changePhoneNum',num);
  },
  checkVerificationCode:({commit,state})=>{
    commit("checkVerificationCode");
  },
  savePatientCustomerId:({commit,state},id)=>{
    commit('savePatientCustomerId',id);
  },
  changeCodeDes:({commit,state},des)=>{
    commit("changeCodeDes",des)
  },
  showToast:({commit,state},json)=>{
    commit("showToast",json);
  },
  setTimeVerificationCode:({commit,state})=>{
    commit('setTimeVerificationCode');
  },
  changeReportDialog:({commit,state},status)=>{
    commit('changeReportDialog');
  },
  consultDoctor:({commit,state})=>{
    commit('consultDoctor');
  },
  savePatientList:({commit,state},list)=>{
    commit('savePatientList',list);
  },
  saveReportData:({commit,state},data)=>{
    commit("saveReportData",data);
  }
};
export  default  actions;
